"""criar todas as tabelas

Revision ID: 5901fc0d0f15
Revises: 
Create Date: 2025-07-13 22:37:12.512442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5901fc0d0f15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistemas_alvo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agravos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sistema_alvo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sistema_alvo_id'], ['sistemas_alvo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_notificacao', sa.String(length=7), nullable=False),
    sa.Column('record', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('agravo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agravo_id'], ['agravos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_notificacao_detalhes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpa_notificacao_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rpa_notificacao_id'], ['rpa_notificacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpa_notificacao_detalhes')
    op.drop_table('rpa_notificacoes')
    op.drop_table('agravos')
    op.drop_table('sistemas_alvo')
    # ### end Alembic commands ###
