name: "🚀 Release and Publish"

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    name: "🔖 Tag & Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout (full history)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Semantic Release
      uses: go-semantic-release/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        changelog-generator-opt: "emojis=true"